import {
  MapPin,
  Phone,
  User,
  ShoppingCart,
  GitCompareArrows,
  Search,
  Menu,
  MessageCircle,
  Home,
  Store,
  Truck,
  ShieldCheck,
  Star,
  Tag,
  BadgeCheck,
  Building2,
  Clock,
  Mail,
  Package,
  CreditCard,
  Gift,
  Sparkles,
  Wallet,
  Laptop,
  Printer,
  RotateCcw,
  Monitor,
  Mouse,
  Headphones,
  Wifi,
  HardDrive,
  Cpu,
  Gamepad2,
  Smartphone,
  Tablet,
  BatteryCharging,
  Keyboard,
  Speaker,
  Plug,
  Server,
  Usb,
  Cable,
  type LucideIcon,
} from "lucide-react";

export const HEADER_ICONS: Record<string, LucideIcon> = {
  mapPin: MapPin,
  phone: Phone,
  user: User,
  cart: ShoppingCart,
  compare: GitCompareArrows,
  search: Search,
  menu: Menu,
  messageCircle: MessageCircle,
  home: Home,
  store: Store,
  truck: Truck,
  shieldCheck: ShieldCheck,
  star: Star,
  tag: Tag,
  badgeCheck: BadgeCheck,
  building: Building2,
  clock: Clock,
  mail: Mail,
  package: Package,
  creditCard: CreditCard,
  gift: Gift,
  sparkles: Sparkles,
  wallet: Wallet,
  laptop: Laptop,
  printer: Printer,
  returns: RotateCcw,
  monitor: Monitor,
  mouse: Mouse,
  headphones: Headphones,
  wifi: Wifi,
  hardDrive: HardDrive,
  cpu: Cpu,
  gamepad: Gamepad2,
  smartphone: Smartphone,
  tablet: Tablet,
  battery: BatteryCharging,
  keyboard: Keyboard,
  speaker: Speaker,
  plug: Plug,
  server: Server,
  usb: Usb,
  cable: Cable,
};

// Maps a category slug to a meaningful icon name (no images, minimal menu).
export const CATEGORY_ICONS: Record<string, string> = {
  ordinateurs: "laptop",
  imprimantes: "printer",
  ecrans: "monitor",
  peripheriques: "mouse",
  "image-son": "headphones",
  reseaux: "wifi",
  stockage: "hardDrive",
  composants: "cpu",
  gaming: "gamepad",
  smartphones: "smartphone",
  tablettes: "tablet",
  energie: "battery",
  accessoires: "package",
  // PC Jahiz actual slugs
  ordinateur: "laptop",
  imprimante: "printer",
  "point-de-vente": "store",
  peripherique: "mouse",
  projection: "monitor",
  reseau: "wifi",
  telephonie: "smartphone",
  connectique: "cable",
  gaming_pc: "gamepad",
};

export function categoryIcon(slug?: string | null): string | undefined {
  return slug ? CATEGORY_ICONS[slug] : undefined;
}

export const HEADER_ICON_OPTIONS = Object.keys(HEADER_ICONS);

export function HeaderIcon({ name, className, style }: { name: string | null | undefined; className?: string; style?: React.CSSProperties }) {
  const Icon = name ? HEADER_ICONS[name] : undefined;
  if (!Icon) return null;
  return <Icon className={className} style={style} />;
}