export const CATS = [
  { slug: "ordinateurs", nameFr: "Ordinateurs & Laptops", nameAr: "الحواسيب واللابتوبات", deck: 1, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786979682/products/hxdhhckcopgih3seiagv.png" },
  { slug: "smartphones", nameFr: "Smartphones", nameAr: "الهواتف الذكية", deck: 2, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786979840/products/pxkem8f2dj2xa3hvnlwu.png" },
  { slug: "tablettes", nameFr: "Tablettes", nameAr: "الأجهزة اللوحية", deck: 3, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786982349/products/jta3ohrxuajcc7og9vj6.png" },
  { slug: "ecrans", nameFr: "Écrans & Moniteurs", nameAr: "الشاشات", deck: 4, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786984586/products/kxyvgelzauh0f8sbcbwi.png" },
  { slug: "composants", nameFr: "Composants PC", nameAr: "مكونات الحاسوب", deck: 5, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786985374/products/yswui9r10p77vtyjw7ac.png" },
  { slug: "peripheriques", nameFr: "Périphériques", nameAr: "الملحقات", deck: 6, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786985300/products/govzrt5dy1avv8xwcygk.png" },
  { slug: "impression", nameFr: "Impression", nameAr: "الطباعة", deck: 7, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786985318/products/vnk2r0tcxx7lk1kjzbvp.png" },
  { slug: "audio", nameFr: "Audio & Casques", nameAr: "الصوتيات والسماعات", deck: 8, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786967297/products/so5zf3a2c7kgtyqbayle.png" },
  { slug: "reseau", nameFr: "Réseau & Connectivité", nameAr: "الشبكات والاتصال", deck: 9, img: "https://res.cloudinary.com/xswbhy0z/image/upload/v1786967318/products/iprqecogbowpucttyk5y.png" },
  { slug: "stockage-externe", nameFr: "Stockage externe", nameAr: "التخزين الخارجي", deck: 10, img: null },
  { slug: "energie", nameFr: "Énergie & Batteries", nameAr: "الطاقة والبطاريات", deck: 11, img: null },
  { slug: "gadgets", nameFr: "Gadgets & Connectés", nameAr: "الأدوات المتصلة", deck: 12, img: null },
  { slug: "accessoires", nameFr: "Accessoires", nameAr: "إكسسوارات", deck: 13, img: null },
];

export const BRANDS = [
  "acer","aoc","asus","baseus","brother","canon","corsair","dlink","dell","epson",
  "gigabyte","google","hp","huawei","intel","jbl","kingston","lenovo","logitech","microsoft",
  "msi","nvidia","philips","samsung","sandisk","seagate","sony","tplink","westerndigital","xerox","xiaomi","apple","amd",
].map((slug) => ({
  slug,
  name: slug === "dlink" ? "D-Link" : slug === "tplink" ? "TP-Link" : slug === "westerndigital" ? "Western Digital" : slug === "kingston" ? "Kingston" : slug.charAt(0).toUpperCase() + slug.slice(1),
}));

const P = (
  slug: string, name: string, brandSlug: string | null, categorySlug: string,
  price: number, oldPrice: number | null, img: string,
  opts: Partial<{ sku: string; taglineFr: string; taglineAr: string; descriptionFr: string; descriptionAr: string; specs: [string, string][]; featured: boolean; isNew: boolean; popularity: number; stock: number }> = {},
) => ({
  slug,
  nameFr: name,
  nameAr: name,
  brandSlug,
  categorySlug,
  price,
  oldPrice,
  discount: oldPrice ? Math.round((1 - price / oldPrice) * 100) : null,
  img,
  sku: opts.sku ?? slug.toUpperCase().replace(/-/g, "-"),
  summaryFr: opts.taglineFr ?? null,
  summaryAr: opts.taglineAr ?? null,
  descriptionFr: opts.descriptionFr ?? null,
  descriptionAr: opts.descriptionAr ?? null,
  specs: opts.specs ? JSON.stringify(opts.specs.map(([k, v]) => ({ k, v }))) : null,
  featured: opts.featured ?? false,
  isNew: opts.isNew ?? false,
  popularity: opts.popularity ?? 50,
  stock: opts.stock ?? 10,
});

const LAPTOP = "https://pngimg.com/uploads/laptop/";

export const PRODUCTS = [
  P("acer-nitro-v16", "Acer Nitro V16", "acer", "ordinateurs", 13999, 15499, LAPTOP + "laptop_PNG5912.png", {
    featured: true, isNew: true, popularity: 95, stock: 7,
    taglineFr: "Le module gaming ultime, conçu pour dominer chaque session.",
    taglineAr: "وحدة الألعاب المطلقة، صُممت للهيمنة على كل جلسة.",
    descriptionFr: "Le PC portable Acer Nitro V16 est l'outil ultime pour les passionnés de jeux vidéo et les professionnels exigeants. Il intègre des composants de dernière génération pour garantir une fluidité exceptionnelle lors de vos sessions de gaming intenses ou de vos tâches créatives complexes. Son système de refroidissement optimisé maintient des performances stables même sous forte charge. Chez PC Jahiz : livraison rapide partout au Maroc, paiement à la livraison et garantie 12 mois.",
    descriptionAr: "حاسوب Acer Nitro V16 المحمول هو الأداة المثلى لعشاق ألعاب الفيديو والمحترفين الباحثين عن أداء استثنائي. يجمع أحدث المكونات لضمان سلاسة مذهلة في جلسات اللعب المكثفة أو المهام الإبداعية المعقدة. نظام التبريد المحسّن يحافظ على أداء مستقر حتى تحت الضغط. لدى PC Jahiz: توصيل سريع لجميع أنحاء المغرب، الدفع عند الاستلام وضمان 12 شهرًا.",
    specs: [["Écran", "16\" FHD+ 165 Hz"], ["Processeur", "Intel Core i7 / Ryzen 7"], ["Carte graphique", "NVIDIA GeForce RTX"], ["RAM", "16 Go DDR5"], ["Stockage", "512 Go SSD NVMe"], ["Clavier", "Rétroéclairé RGB AZERTY"]],
  }),
  P("acer-aspire-5", "Acer Aspire 5", "acer", "ordinateurs", 6799, 7499, LAPTOP + "laptop_PNG5909.png", {
    isNew: true, popularity: 80, stock: 12,
    taglineFr: "L'essentiel du quotidien, propulsé en orbite.",
    taglineAr: "أساسيات يومك، مدفوعة إلى المدار.",
    descriptionFr: "L'Acer Aspire 5 est le compagnon idéal pour le travail, les études et le divertissement. Fin, léger et réactif, il embarque un écran lumineux et une autonomie longue durée. Disponible chez PC Jahiz avec livraison 24–48h partout au Maroc et paiement à la livraison.",
    descriptionAr: "Acer Aspire 5 هو الرفيق المثالي للعمل والدراسة والترفيه. نحيف وخفيف وسريع الاستجابة، مع شاشة مشرقة وبطارية تدوم طويلًا. متوفر لدى PC Jahiz مع توصيل خلال 24-48 ساعة لجميع أنحاء المغرب والدفع عند الاستلام.",
    specs: [["Écran", "15.6\" FHD IPS"], ["Processeur", "Intel Core i5"], ["RAM", "8 Go"], ["Stockage", "512 Go SSD"], ["Poids", "1.7 kg"]],
  }),
  P("msi-modern-14", "MSI Modern 14", "msi", "ordinateurs", 6499, null, LAPTOP + "laptop_PNG5906.png", {
    popularity: 70, stock: 9,
    taglineFr: "Élégance nomade, puissance discrète.",
    taglineAr: "أناقة متنقلة، قوة هادئة.",
    descriptionFr: "Le MSI Modern 14 allie portabilité et performance pour les créateurs et professionnels en déplacement. Châssis fin, écran précis et réactivité remarquable au quotidien.",
    descriptionAr: "يجمع MSI Modern 14 بين سهولة التنقل والأداء للمبدعين والمحترفين أثناء التنقل. هيكل نحيف وشاشة دقيقة واستجابة رائعة يوميًا.",
    specs: [["Écran", "14\" FHD IPS"], ["Processeur", "Intel Core i5 / Ryzen 5"], ["RAM", "16 Go"], ["Stockage", "512 Go SSD"], ["Poids", "1.4 kg"]],
  }),
  P("msi-katana-gf63", "MSI Katana GF63", "msi", "ordinateurs", 12999, 14499, LAPTOP + "laptop_PNG5903.png", {
    isNew: true, popularity: 85, stock: 6,
    taglineFr: "La lame du gaming, affûtée pour la victoire.",
    taglineAr: "نصل الألعاب، مشحوذ للانتصار.",
    descriptionFr: "La MSI Katana GF63 est taillée pour le gaming : GPU dédié, écran haute fréquence et refroidissement musclé. Une machine de guerre au prix juste, livrée partout au Maroc par PC Jahiz.",
    descriptionAr: "MSI Katana GF63 مصممة للألعاب: بطاقة رسومات مخصصة وشاشة عالية التردد وتبريد قوي. آلة حرب بسعر عادل، تصلك أينما كنت في المغرب عبر PC Jahiz.",
    specs: [["Écran", "15.6\" FHD 144 Hz"], ["Carte graphique", "NVIDIA GeForce RTX"], ["RAM", "16 Go"], ["Stockage", "512 Go SSD NVMe"]],
  }),
  P("asus-rog-strix", "Asus ROG Strix G16", "asus", "ordinateurs", 21999, 24999, LAPTOP + "laptop_PNG5900.png", {
    featured: true, popularity: 98, stock: 4,
    taglineFr: "Le vaisseau amiral du gaming. Rien d'autre ne compte.",
    taglineAr: "السفينة الأم للألعاب. لا شيء آخر يهم.",
    descriptionFr: "L'Asus ROG Strix G16 est le sommet de la chaîne alimentaire gaming : écran 165 Hz, RTX dernière génération, châssis RGB agressif et refroidissement Tri-Fan. Pour les joueurs qui refusent tout compromis.",
    descriptionAr: "Asus ROG Strix G16 هو قمة السلسلة الغذائية للألعاب: شاشة 165 هرتز، وبطاقة RTX من الجيل الأخير، وهيكل RGB هجومي وتبريد ثلاثي المراوح. للاعبين الذين يرفضون أي مساومة.",
    specs: [["Écran", "16\" QHD+ 165 Hz"], ["Carte graphique", "NVIDIA GeForce RTX 40"], ["RAM", "16 Go DDR5"], ["Stockage", "1 To SSD NVMe"], ["Éclairage", "Aura Sync RGB"]],
  }),
  P("asus-vivobook-15", "Asus Vivobook 15", "asus", "ordinateurs", 6999, null, LAPTOP + "laptop_PNG101835.png", {
    popularity: 75, stock: 14,
    taglineFr: "Le polyvalent qui ne recule devant rien.",
    taglineAr: "المتعدد المواهب الذي لا يتراجع عن شيء.",
    descriptionFr: "L'Asus Vivobook 15 est le laptop de tous les jours par excellence : performant, stylé et abordable. Parfait pour le télétravail, les cours et le streaming.",
    descriptionAr: "Asus Vivobook 15 هو حاسوب كل يوم بامتياز: قوي وأنيق وبسعر معقول. مثالي للعمل عن بعد والدروس والمشاهدة.",
    specs: [["Écran", "15.6\" FHD"], ["Processeur", "Intel Core i5"], ["RAM", "8 Go"], ["Stockage", "512 Go SSD"]],
  }),
  P("dell-xps-13", "Dell XPS 13", "dell", "ordinateurs", 16999, 18999, LAPTOP + "laptop_PNG101832.png", {
    featured: true, popularity: 90, stock: 5,
    taglineFr: "Le luxe technologique à l'état pur.",
    taglineAr: "الفخامة التقنية في أنقى صورها.",
    descriptionFr: "Le Dell XPS 13 est la référence absolue des ultrabooks : écran InfinityEdge quasi sans bords, châssis en aluminium usiné et autonomie marathon. L'outil des dirigeants et des créatifs exigeants.",
    descriptionAr: "Dell XPS 13 هو المرجع المطلق للألترابوك: شاشة InfinityEdge شبه بلا حواف، وهيكل من الألمنيوم المشغول وبطارية ماراثونية. أداة المديرين والمبدعين المتطلبين.",
    specs: [["Écran", "13.4\" FHD+ InfinityEdge"], ["Processeur", "Intel Core i7"], ["RAM", "16 Go LPDDR5"], ["Stockage", "512 Go SSD"], ["Châssis", "Aluminium usiné CNC"]],
  }),
  P("dell-inspiron-15", "Dell Inspiron 15", "dell", "ordinateurs", 7499, 8299, LAPTOP + "laptop_PNG101829.png", {
    isNew: true, popularity: 72, stock: 11,
    taglineFr: "La fiabilité Dell, au prix du quotidien.",
    taglineAr: "موثوقية Dell بسعر يومي.",
    descriptionFr: "Le Dell Inspiron 15 offre l'équilibre parfait entre performance et prix pour toute la famille : bureautique, études, divertissement — tout y passe sans effort.",
    descriptionAr: "يقدم Dell Inspiron 15 التوازن المثالي بين الأداء والسعر لجميع أفراد الأسرة: المكتب والدراسة والترفيه — كل شيء يعمل دون عناء.",
    specs: [["Écran", "15.6\" FHD"], ["Processeur", "Intel Core i5"], ["RAM", "8 Go"], ["Stockage", "256 Go SSD"]],
  }),
  P("hp-omen-16", "HP Omen 16", "hp", "ordinateurs", 14999, 16999, LAPTOP + "laptop_PNG101826.png", {
    featured: true, popularity: 92, stock: 6,
    taglineFr: "L'ombre qui frappe plus fort que la lumière.",
    taglineAr: "الظل الذي يضرب بقوة أكثر من الضوء.",
    descriptionFr: "Le HP Omen 16 combine un design sombre et élégant avec une puissance de jeu dévastatrice. Écran haute fréquence, GPU RTX et Omen Tempest Cooling pour rester glacial sous pression.",
    descriptionAr: "يجمع HP Omen 16 بين تصميم داكن وأنيق وقوة لعب مدمرة. شاشة عالية التردد وبطاقة RTX وتبريد Omen Tempest للبقاء باردًا تحت الضغط.",
    specs: [["Écran", "16.1\" QHD 165 Hz"], ["Carte graphique", "NVIDIA GeForce RTX"], ["RAM", "16 Go DDR5"], ["Stockage", "1 To SSD"], ["Refroidissement", "Omen Tempest"]],
  }),
  P("hp-pavilion-15", "HP Pavilion 15", "hp", "ordinateurs", 7999, 8999, LAPTOP + "laptop_PNG101823.png", {
    popularity: 78, stock: 10,
    taglineFr: "Le classique qui ne déçoit jamais.",
    taglineAr: "الكلاسيكي الذي لا يخيب أبدًا.",
    descriptionFr: "Le HP Pavilion 15 est la valeur sûre : un laptop complet, fiable et élégant pour le travail comme pour les loisirs, avec la qualité de construction HP.",
    descriptionAr: "HP Pavilion 15 هو الخيار المضمون: حاسوب متكامل وموثوق وأنيق للعمل والترفيه، بجودة تصنيع HP.",
    specs: [["Écran", "15.6\" FHD IPS"], ["Processeur", "Intel Core i5"], ["RAM", "16 Go"], ["Stockage", "512 Go SSD"]],
  }),
  P("airpods-pro-2", "AirPods Pro 2", "apple", "audio", 2799, 3199, "https://pngimg.com/uploads/airPods/airPods_PNG40.png", {
    featured: true, popularity: 96, stock: 20,
    taglineFr: "Le silence. Puis la musique. Rien d'autre.",
    taglineAr: "الصمت. ثم الموسيقى. لا شيء آخر.",
    descriptionFr: "Les AirPods Pro 2 offrent une réduction de bruit active deux fois plus efficace, un son spatial personnalisé et jusqu'à 30 heures d'écoute avec le boîtier MagSafe. L'audio premium dans sa forme la plus pure.",
    descriptionAr: "توفر AirPods Pro 2 إلغاء ضوضاء نشطًا أكثر فعالية بمرتين، وصوتًا مكانيًا مخصصًا وحتى 30 ساعة من الاستماع مع علبة MagSafe. الصوت الفاخر في أنقى صوره.",
    specs: [["Réduction de bruit", "Active ×2"], ["Autonomie", "6h + 24h (boîtier)"], ["Puce", "Apple H2"], ["Boîtier", "MagSafe / USB-C"], ["Résistance", "IP54"]],
  }),
  P("macbook-air-m2", "MacBook Air M2", "apple", "ordinateurs", 12999, 13999, LAPTOP + "laptop_PNG101820.png", {
    featured: true, popularity: 94, stock: 8,
    taglineFr: "Impossiblement fin. Incroyablement puissant.",
    taglineAr: "نحيف بشكل مستحيل. قوي بشكل لا يصدق.",
    descriptionFr: "Le MacBook Air M2 redéfinit le portable : puce Apple M2 fulgurante, 18 heures d'autonomie, design sans ventilateur totalement silencieux et écran Liquid Retina sublime.",
    descriptionAr: "يعيد MacBook Air M2 تعريف الحاسوب المحمول: شريحة Apple M2 الصاروخية، و18 ساعة من البطارية، وتصميم بلا مروحة صامت تمامًا وشاشة Liquid Retina رائعة.",
    specs: [["Puce", "Apple M2 8 cœurs"], ["Écran", "13.6\" Liquid Retina"], ["RAM", "8 Go unifiée"], ["Stockage", "256 Go SSD"], ["Autonomie", "18 heures"]],
  }),
  P("thinkpad-e14", "Lenovo ThinkPad E14", "lenovo", "ordinateurs", 9999, 11499, LAPTOP + "laptop_PNG101808.png", {
    popularity: 82, stock: 9,
    taglineFr: "La légende du business, indestructible.",
    taglineAr: "أسطورة الأعمال، لا تُقهر.",
    descriptionFr: "Le ThinkPad E14 hérite de 30 ans de fiabilité légendaire : clavier mythique, certification militaire MIL-STD et sécurité renforcée. Le choix des professionnels qui ne plaisantent pas.",
    descriptionAr: "يرث ThinkPad E14 ثلاثين عامًا من الموثوقية الأسطورية: لوحة مفاتيح ميثاقية وشهادة عسكرية MIL-STD وأمان معزز. خيار المحترفين الجادين.",
    specs: [["Écran", "14\" FHD+"], ["Processeur", "Intel Core i5 / Ryzen 5"], ["RAM", "16 Go"], ["Stockage", "512 Go SSD"], ["Certification", "MIL-STD-810H"]],
  }),
  P("wh-1000xm5", "Sony WH-1000XM5", "sony", "audio", 3499, 3999, "https://pngimg.com/uploads/headphones/headphones_PNG101983.png", {
    featured: true, popularity: 93, stock: 15,
    taglineFr: "La meilleure réduction de bruit au monde. Point.",
    taglineAr: "أفضل إلغاء ضوضاء في العالم. نقطة.",
    descriptionFr: "Le Sony WH-1000XM5 est le casque à réduction de bruit de référence : 8 microphones, 30 heures d'autonomie et un son d'une clarté exceptionnelle. Le silence devient un luxe portable.",
    descriptionAr: "Sony WH-1000XM5 هو سماعة إلغاء الضوضاء المرجعية: 8 ميكروفونات و30 ساعة بطارية وصوت فائق الوضوح. الصمت يصبح رفاهية متنقلة.",
    specs: [["Réduction de bruit", "8 micros, double processeur"], ["Autonomie", "30 heures"], ["Audio", "Hi-Res, LDAC"], ["Poids", "250 g"]],
  }),
  P("galaxy-s24", "Samsung Galaxy S24", "samsung", "smartphones", 7499, null, "https://pngimg.com/uploads/phone/phone_PNG49056.png", {
    featured: true, isNew: true, popularity: 91, stock: 13,
    taglineFr: "L'IA Galaxy dans la paume de votre main.",
    taglineAr: "ذكاء Galaxy الاصطناعي في راحة يدك.",
    descriptionFr: "Le Galaxy S24 inaugure l'ère Galaxy AI : traduction en direct, retouche photo par IA et écran Dynamic AMOLED 2X éclatant. Le flagship compact qui pense pour vous.",
    descriptionAr: "يفتتح Galaxy S24 عصر Galaxy AI: ترجمة فورية وتحرير صور بالذكاء الاصطناعي وشاشة Dynamic AMOLED 2X ساطعة. الهاتف الرائد المدمج الذي يفكر عنك.",
    specs: [["Écran", "6.2\" Dynamic AMOLED 2X 120 Hz"], ["Processeur", "Snapdragon 8 Gen 3"], ["Photo", "50 MP triple capteur"], ["Batterie", "4000 mAh"], ["IA", "Galaxy AI"]],
  }),
  P("iphone-15", "iPhone 15", "apple", "smartphones", 7999, 8999, "https://pngimg.com/uploads/phone/phone_PNG49059.png", {
    popularity: 89, stock: 11,
    taglineFr: "Dynamic Island. USB-C. Le nouvel iPhone.",
    taglineAr: "Dynamic Island. USB-C. الآيفون الجديد.",
    descriptionFr: "L'iPhone 15 apporte la Dynamic Island, un appareil photo 48 MP époustouflant et l'USB-C enfin universel — le tout propulsé par la puce A16 Bionic.",
    descriptionAr: "يجلب iPhone 15 ميزة Dynamic Island وكاميرا 48 ميجابكسل مذهلة ومنفذ USB-C أخيرًا — كل ذلك مدفوع بشريحة A16 Bionic.",
    specs: [["Écran", "6.1\" Super Retina XDR"], ["Puce", "A16 Bionic"], ["Photo", "48 MP"], ["Connecteur", "USB-C"], ["Bouton", "Dynamic Island"]],
  }),
];

export const REVIEWS: { slug: string; author: string; city: string; rating: number; comment: string }[] = [
  { slug: "asus-rog-strix", author: "Yassine B.", city: "Casablanca", rating: 5, comment: "Machine de guerre. Livré en 24h à Casa, paiement à la livraison nickel. Les jeux tournent à fond." },
  { slug: "macbook-air-m2", author: "Salma E.", city: "Rabat", rating: 5, comment: "Commandée lundi, reçue mardi. Le MacBook est authentique et le service client sur WhatsApp très réactif." },
  { slug: "wh-1000xm5", author: "Omar T.", city: "Marrakech", rating: 5, comment: "La réduction de bruit est irréelle. Emballage soigné, prix imbattable en MAD." },
  { slug: "galaxy-s24", author: "Khadija M.", city: "Tanger", rating: 4, comment: "Super téléphone, livraison rapide. Je retire une étoile car je voulais une autre couleur." },
  { slug: "acer-nitro-v16", author: "Ayoub R.", city: "Fès", rating: 5, comment: "Rapport qualité-prix imbattable pour le gaming. Garantie 12 mois rassurante." },
  { slug: "hp-omen-16", author: "Mehdi K.", city: "Agadir", rating: 5, comment: "Froid même après 4h de jeu. PC Jahiz livre vraiment partout au Maroc, testé à Agadir." },
];

